CREATE DATABASE IF NOT EXISTS edusphere;
USE edusphere;

CREATE TABLE IF NOT EXISTS users (
	id INT PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(120) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	full_name VARCHAR(120) NOT NULL,
	department VARCHAR(120) NOT NULL,
	role ENUM('student', 'admin') NOT NULL DEFAULT 'student',
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS role ENUM('student', 'admin') NOT NULL DEFAULT 'student';

CREATE TABLE IF NOT EXISTS courses (
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(160) NOT NULL,
	instructor VARCHAR(120) NOT NULL,
	room VARCHAR(40),
	progress TINYINT UNSIGNED DEFAULT 0,
	UNIQUE KEY unique_course_title (title)
);

CREATE TABLE IF NOT EXISTS attendance (
	id INT PRIMARY KEY AUTO_INCREMENT,
	user_id INT NOT NULL,
	course_id INT NOT NULL,
	attended BOOLEAN NOT NULL DEFAULT TRUE,
	class_date DATE NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS assignments (
	id INT PRIMARY KEY AUTO_INCREMENT,
	user_id INT NOT NULL,
	title VARCHAR(180) NOT NULL,
	course_name VARCHAR(120) NOT NULL,
	due_date DATE NOT NULL,
	completed BOOLEAN NOT NULL DEFAULT FALSE,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notices (
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(180) NOT NULL,
	body TEXT NOT NULL,
	published_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
